# Generated by Django 3.0.6 on 2020-07-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglotmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameralist',
            options={'managed': False},
        ),
    ]
