# Generated by Django 3.0.6 on 2020-07-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglotmanager', '0003_auto_20200701_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameralist',
            options={'managed': False},
        ),
    ]
